In [6]:
import torch
import torch.nn as nn
import numpy as np
import csv

In [7]:
train_path = './HW1.train.csv'  # path to training data
with open(train_path, 'r') as f:
    data = list(csv.reader(f))
    data = np.array(data[1:])[:, 1:].astype(float)

data[:, 40]

array([0.81461  , 0.8389952, 0.8978015, ..., 1.5926473, 1.6634515,
       1.9039694])

In [8]:
feats_sta = list(range(40))         # 40 states
feats_symp1 = list(range(40,44))    # day1 symptom like Covid-19
feats_testp1 = [57]                 # day2 tested_positive
feats_symp2 = list(range(58,62))    # day2 symptom like Covid-19
feats_testp2 = [75]                 # day2 tested_positive 
feats_symp3 = list(range(76,80))    # day3 symptom like Covid-19

feats = feats_sta + feats_symp1 + feats_testp1 + feats_symp2 + feats_testp2 + feats_symp3

target = data[:, -1]
data_train = data[:, feats]
data_train[0]

array([ 1.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.81461  ,  0.7713562, 25.6489069, 21.2420632, 19.586492 ,
        0.8389952,  0.8077665, 25.6791006, 21.2802696, 20.1518381,
        0.8978015,  0.8878931, 26.0605436, 21.5038315])

In [9]:
feats_test = [f+1 for f in feats]
data_test = data[:, feats]

data_test_row1 = data_test[0]
data_test_row1

array([ 1.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.81461  ,  0.7713562, 25.6489069, 21.2420632, 19.586492 ,
        0.8389952,  0.8077665, 25.6791006, 21.2802696, 20.1518381,
        0.8978015,  0.8878931, 26.0605436, 21.5038315])