# 2. Data Manipulation

## 2.1 Getting Started

In [1]:
import torch

In [2]:
# create a vector from 0 to 12, including the first 0 but not including the last
x = torch.arange(15, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14.])

In [3]:
# return vector shape
x.shape

torch.Size([15])

In [4]:
# return the total number of elements in x
x.numel()

15

In [5]:
# reshape x into the given format (3 row 4 column)
X = x.reshape(3, 5)
X

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [6]:
# tensor is a data format created by pytorch, it could be a value/vector/matrix
# create a matrix with element 0
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# create a matrix with element 1
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

# 2.2 Operations

In [8]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
# element-wise plus, minus, multiply, divide, power
x + y, x - y, x * y, x / y, x ** y # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [9]:
# exponentiation
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [10]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# concatenation along dimension 0 
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [11]:
# concatenation along dimension 1
torch.cat((X,Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [12]:
# element-wise logic
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
# the sum of all the elements
X.sum()

tensor(66.)

## 2.3 Broadcasting Mechanism

In [14]:
# Some functions can be used even if two variables have different shapes 
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [15]:
# Automatically expand the their size and then compute output
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.4 Indexing and Slicing

In [19]:
# obtain value/slice of a tensor
# Note: contain the start value, don't contain the end value
# Minus one is the last one
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
# Give it a new value in the position of row 1 column 2
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
# Assign a same value to a slice
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.5 Saving Memory

In [22]:
# id funtion returns the address of a variable
before = id(Y)
Y = Y + X
# address has been changed. Y has been given a new address.
id(Y) == before

False

In [27]:
# create a new matrix with the same shape as Y
Z = torch.zeros_like(Y)
print(Z)
print('id(Z):', id(Z))
# use inplace operation, doesn't change the address of Z
Z[:] = X + Y
print('id(Z):', id(Z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 2783356041312
id(Z): 2783356041312


In [28]:
before = id(X)
# inplace operation
X += Y
id(X) == before

True

## 2.6 Conversion to Other Python Objects

In [29]:
# change variable class between 
# numpy (format usually used by codes that run in a cpu environment) 
# and torch tensor (format used by codes that run in a gpu environment)
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [32]:
a = torch.tensor([3.5])
# Transformation between value and vector
a, a.item()
# Transformation between different data types
float(a), int(a)

(3.5, 3)

# 3. Data Preprocessing

## 3.1 Reading the Dataset

In [34]:
import os
# "./" means the current folder
# ./data
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
# ./data/house_tiny.csv
data_file = os.path.join('.', 'data', 'house_tiny.csv')
# NA means missing data
with open(data_file, 'w') as f:
 f.write('NumRooms,Viewed,Alley,Price\n') # Column names
 f.write('NA,3,Pave,127500\n') # Each row represents a data example
 f.write('2,3,NA,106000\n')
 f.write('4,NA,NA,178100\n')
 f.write('NA,3,NA,140000\n')

In [35]:
# If pandas is not installed, just uncomment the following line:
# !pip install pandas
# pandas is usually used for data loading and processing
import pandas as pd
data = pd.read_csv(data_file)
# NaN means missing data
print(data)

   NumRooms  Viewed Alley   Price
0       NaN     3.0  Pave  127500
1       2.0     3.0   NaN  106000
2       4.0     NaN   NaN  178100
3       NaN     3.0   NaN  140000


## 3.2 Handling Missing Data

In [36]:
a, b = data.iloc[:, :2], data.iloc[:, 2:]
# fill the missing data with the given data (mean of each column)
a = a.fillna(a.mean())
print(a)

   NumRooms  Viewed
0       3.0     3.0
1       2.0     3.0
2       4.0     3.0
3       3.0     3.0


In [37]:
print(b)

  Alley   Price
0  Pave  127500
1   NaN  106000
2   NaN  178100
3   NaN  140000


In [38]:
# classify different category of strings, NaN is treated as one category
b = pd.get_dummies(b, dummy_na=True)
print(b)

    Price  Alley_Pave  Alley_nan
0  127500        True      False
1  106000       False       True
2  178100       False       True
3  140000       False       True


## 3.3 Conversion to the Tensor Format

In [39]:
#convert to tensor format
import torch
X, y = torch.tensor(a.values), torch.tensor(b.values.astype(int))
X, y

(tensor([[3., 3.],
         [2., 3.],
         [4., 3.],
         [3., 3.]], dtype=torch.float64),
 tensor([[127500,      1,      0],
         [106000,      0,      1],
         [178100,      0,      1],
         [140000,      0,      1]], dtype=torch.int32))